version: 2

updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - flutter

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - android

  - package-ecosystem: cocoapods
    directory: /ios
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ios

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
