import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _outputPath = 'THIRD_PARTY_NOTICES.md';
const _packageConfigPath = '.dart_tool/package_config.json';
const _lockfilePath = 'pubspec.lock';
const _expectedFlutterVersion = '3.41.4';

void main(List<String> arguments) {
  final checkOnly = arguments.contains('--check');
  final output = _generate();
  final outputFile = File(_outputPath);

  if (checkOnly) {
    if (!outputFile.existsSync() || outputFile.readAsStringSync() != output) {
      stderr.writeln(
        '$_outputPath is stale. Run: '
        'dart run tool/generate_third_party_notices.dart',
      );
      exitCode = 1;
    }
    return;
  }

  outputFile.writeAsStringSync(output);
}

String _generate() {
  final packageConfigFile = File(_packageConfigPath);
  if (!packageConfigFile.existsSync()) {
    throw StateError('Run flutter pub get before generating notices.');
  }

  final lockVersions = _readLockVersions(File(_lockfilePath));
  final config = jsonDecode(packageConfigFile.readAsStringSync()) as Map;
  final configUri = packageConfigFile.absolute.uri;
  final configuredPackages = <String, Map<String, Object?>>{
    for (final raw in config['packages'] as List)
      (raw as Map)['name']! as String: raw.cast<String, Object?>(),
  };
  _verifyFlutterVersion(configuredPackages, configUri);
  final packages = <_PackageNotice>[];
  final missingLicenses = <String>[];

  final lockedNames = lockVersions.keys.toList()..sort();
  for (final name in lockedNames) {
    final package = configuredPackages[name];
    if (package == null) {
      throw StateError(
        '$name is in $_lockfilePath but not $_packageConfigPath.',
      );
    }

    final rootUri = configUri.resolve(package['rootUri']! as String);
    final licenseFiles = _findLicenseFiles(Directory.fromUri(rootUri));
    if (licenseFiles.isEmpty) {
      missingLicenses.add(name);
      continue;
    }

    packages.add(
      _PackageNotice(
        name: name,
        version: lockVersions[name]!,
        documents: [
          for (final file in licenseFiles)
            _LicenseDocument(
              label: file.uri.pathSegments.last,
              text: _normalize(file.readAsStringSync()),
            ),
        ],
      ),
    );
  }

  if (missingLicenses.isNotEmpty) {
    throw StateError(
      'No top-level license document found for: ${missingLicenses.join(', ')}',
    );
  }

  packages.sort((left, right) => left.name.compareTo(right.name));
  final grouped = <String, _GroupedDocument>{};
  for (final package in packages) {
    for (final document in package.documents) {
      final digest = sha256.convert(utf8.encode(document.text)).toString();
      final group = grouped.putIfAbsent(
        digest,
        () => _GroupedDocument(digest: digest, text: document.text),
      );
      group.packages.add(
        '${package.name} ${package.version} (${document.label})',
      );
      package.documentIds.add(digest.substring(0, 12));
    }
  }

  final buffer = StringBuffer()
    ..writeln('# Third-party notices')
    ..writeln()
    ..writeln(
      'This file records the third-party packages resolved by `pubspec.lock` '
      'and their distributed top-level license or notice texts.',
    )
    ..writeln()
    ..writeln(
      'Generation is pinned to Flutter $_expectedFlutterVersion so SDK '
      'licence data is reproducible across platforms and CI runners.',
    )
    ..writeln()
    ..writeln(
      'It is generated by `tool/generate_third_party_notices.dart`. Regenerate '
      'it after changing dependencies:',
    )
    ..writeln()
    ..writeln('```bash')
    ..writeln('flutter pub get')
    ..writeln('dart run tool/generate_third_party_notices.dart')
    ..writeln('```')
    ..writeln()
    ..writeln(
      'The application also exposes Flutter\'s runtime licence registry from '
      'Settings → Open-source licences.',
    )
    ..writeln()
    ..writeln('## Resolved packages')
    ..writeln()
    ..writeln('| Package | Version | Notice IDs |')
    ..writeln('|---|---:|---|');

  for (final package in packages) {
    buffer.writeln(
      '| `${package.name}` | `${package.version}` | '
      '${package.documentIds.map((id) => '`$id`').join(', ')} |',
    );
  }

  buffer
    ..writeln()
    ..writeln('## License and notice texts')
    ..writeln();

  final groups = grouped.values.toList()
    ..sort((left, right) => left.digest.compareTo(right.digest));
  for (final group in groups) {
    final id = group.digest.substring(0, 12);
    group.packages.sort();
    buffer
      ..writeln('### Notice `$id`')
      ..writeln()
      ..writeln('SHA-256: `${group.digest}`')
      ..writeln()
      ..writeln('Applies to: ${group.packages.join(', ')}')
      ..writeln();
    for (final line in const LineSplitter().convert(group.text)) {
      buffer.writeln('    $line');
    }
    buffer.writeln();
  }

  return buffer.toString();
}

void _verifyFlutterVersion(
  Map<String, Map<String, Object?>> configuredPackages,
  Uri configUri,
) {
  final flutterPackage = configuredPackages['flutter'];
  if (flutterPackage == null) {
    throw StateError('Flutter is missing from $_packageConfigPath.');
  }

  final flutterRoot = Directory.fromUri(
    configUri.resolve(flutterPackage['rootUri']! as String),
  ).parent.parent;
  final versionFile = File(
    '${flutterRoot.path}${Platform.pathSeparator}bin${Platform.pathSeparator}'
    'cache${Platform.pathSeparator}flutter.version.json',
  );
  if (!versionFile.existsSync()) {
    throw StateError('Cannot determine the Flutter SDK version.');
  }

  final versionJson = jsonDecode(versionFile.readAsStringSync()) as Map;
  final actualVersion = versionJson['flutterVersion'];
  if (actualVersion != _expectedFlutterVersion) {
    throw StateError(
      'Third-party notices require Flutter $_expectedFlutterVersion; '
      'found $actualVersion.',
    );
  }
}

Map<String, String> _readLockVersions(File lockfile) {
  final versions = <String, String>{};
  String? currentPackage;
  for (final line in lockfile.readAsLinesSync()) {
    final packageMatch = RegExp(r'^  ([a-zA-Z0-9_]+):$').firstMatch(line);
    if (packageMatch != null) {
      currentPackage = packageMatch.group(1);
      continue;
    }
    final versionMatch = RegExp(
      r'^    version: "?([^"\s]+)"?$',
    ).firstMatch(line);
    if (currentPackage != null && versionMatch != null) {
      versions[currentPackage] = versionMatch.group(1)!;
    }
  }
  return versions;
}

List<File> _findLicenseFiles(Directory packageRoot) {
  var directory = packageRoot.absolute;
  for (var depth = 0; depth < 4; depth += 1) {
    if (!directory.existsSync()) break;
    final matches =
        directory.listSync(followLinks: false).whereType<File>().where((file) {
          final name = file.uri.pathSegments.last.toUpperCase();
          return name == 'LICENSE' ||
              name.startsWith('LICENSE.') ||
              name == 'COPYING' ||
              name.startsWith('COPYING.') ||
              name == 'NOTICE' ||
              name.startsWith('NOTICE.');
        }).toList()..sort((left, right) => left.path.compareTo(right.path));
    if (matches.isNotEmpty) return matches;

    final parent = directory.parent;
    if (parent.path == directory.path) break;
    directory = parent;
  }
  return const [];
}

String _normalize(String text) =>
    '${text.replaceAll('\r\n', '\n').trimRight()}\n';

final class _PackageNotice {
  _PackageNotice({
    required this.name,
    required this.version,
    required this.documents,
  });

  final String name;
  final String version;
  final List<_LicenseDocument> documents;
  final List<String> documentIds = [];
}

final class _LicenseDocument {
  const _LicenseDocument({required this.label, required this.text});

  final String label;
  final String text;
}

final class _GroupedDocument {
  _GroupedDocument({required this.digest, required this.text});

  final String digest;
  final String text;
  final List<String> packages = [];
}
