import 'dart:typed_data';

import 'package:dio/dio.dart';

import '../../../../core/storage/secure_token_storage.dart';
import '../../../../core/utils/app_logger.dart';
import '../../../../core/utils/jwt_claims.dart';
import '../../../unlock/data/datasources/account_remote_datasource.dart';
import '../../../vault/domain/entities/vault_entity.dart';
import '../../../vault/data/services/vault_crypto_service.dart';
import '../datasources/onboarding_remote_datasource.dart';

/// Idempotently provisions the encrypted default vault on the client.
///
/// The plaintext Vault keys are generated by [VaultCryptoService]. Only the
/// authenticated encrypted protocol request is sent to the backend. A
/// persisted boolean tracks a pending retry, but no key material is ever
/// written to storage.
class DefaultVaultProvisioner {
  DefaultVaultProvisioner({
    required this.remoteDatasource,
    required this.vaultCryptoService,
    required this.tokenStorage,
    required this.accountRemoteDatasource,
  });

  final OnboardingRemoteDatasource remoteDatasource;
  final VaultCryptoService vaultCryptoService;
  final SecureTokenStorage tokenStorage;
  final AccountRemoteDatasource accountRemoteDatasource;

  /// Whether registration explicitly left a default vault to be created.
  Future<bool> get isRequired async =>
      await tokenStorage.defaultVaultProvisioned == false;

  Future<void> ensureFromPrivateKey({
    required Uint8List privateKey,
    required String name,
  }) async {
    if (await tokenStorage.defaultVaultProvisioned == true) return;

    await _submit(name: name, privateKey: privateKey);
  }

  Future<void> _submit({
    required String name,
    required Uint8List privateKey,
  }) async {
    if (privateKey.length != 32) {
      throw const FormatException('Member private key must be 32 bytes');
    }
    final accessToken = await tokenStorage.accessToken;
    final organizationId = accessToken == null
        ? null
        : JwtClaims.organizationIdFrom(accessToken);
    final account = await accountRemoteDatasource.getAccount();
    final memberKeyVersion = account.memberKeyVersion;
    if (organizationId == null ||
        memberKeyVersion == null ||
        memberKeyVersion < 1) {
      throw const FormatException('Missing current Member key context');
    }
    final challenge = await remoteDatasource.issueVaultCreationChallenge();
    final vaultId = challenge['vaultId'];
    if (vaultId is! String || vaultId.isEmpty) {
      throw const FormatException('Malformed Vault creation challenge');
    }
    CreatedVaultBundle? bundle;
    try {
      bundle = await vaultCryptoService.createVaultBundle(
        organizationId: organizationId,
        memberId: account.userId,
        memberKeyVersion: memberKeyVersion,
        vaultId: vaultId,
        memberPrivateKey: privateKey,
        name: name,
        grantMode: GrantMode.granular,
      );
      AppLogger.d('Onboarding', 'POST /api/account/default-vault');
      await remoteDatasource.createDefaultVault(
        Map<String, dynamic>.from(bundle.request.toJson()),
      );
      AppLogger.i('Onboarding', 'Default vault created');
    } on DioException catch (error) {
      if (error.response?.statusCode != 409) rethrow;
      AppLogger.i(
        'Onboarding',
        'Default vault already exists (409) - skipping',
      );
    } finally {
      bundle?.vaultKey.fillRange(0, bundle.vaultKey.length, 0);
      bundle?.vaultDiscoveryKey.fillRange(
        0,
        bundle.vaultDiscoveryKey.length,
        0,
      );
    }

    await tokenStorage.setDefaultVaultProvisioned(true);
  }
}
